#!/usr/bin/env bash
declare -r API_URL="https://pokeapi.co/api/v2/pokemon/Pikachu/"
declare -r OUTPUT_FILE="data.json"
declare -r ERROR_FILE="errors.txt"

STATUS_CODE=$(curl -s -w "%{http_code}" -o "$OUTPUT_FILE" $"$API_URL")

if [ ${STATUS_CODE} -eq 200 ]; then
  echo "data of Pikachu saved in $OUTPUT_FILE"
else
  echo "request failed with status code $STATUS_CODE" | tee -a ${ERROR_FILE}
  rm -f ${OUTPUT_FILE}
  fi