#!/usr/bin/env bash

arr=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
declare -r API_URL="https://pokeapi.co/api/v2/pokemon/"
retry(){
  local max_attempt=3
  local current_attempt=1
  local url="$1"
  local output_file="$2"
  while (( current_attempt <= max_attempt )); do
    echo "fetching data for $url $current_attempt attempt"
    if curl -s -f -o "pokemon_data/$output_file" "$url"; then
      echo "success at attempt $current_attempt"
      return 0
    else
      echo "failed at attempt $current_attempt"
      ((attempt++))
      sleep 2
    fi
    echo "🚨 Error: Failed to fetch data for $url after $max_attempt attempts"
  done
  return 1
}
mkdir -p pokemon_data
fetch_one(){
  url=$1
  file=$2
  retry "$url" "$file"
}
for f in "${arr[@]}"; do
  url="$API_URL$f"
  file="$f.json"
  fetch_one "$url" "$file" &
done

wait
echo "parallel processing done"

for pid in $(jobs -p); do
  kill "$pid"
done
