#!/usr/bin/env bash

arr=("Bulbasaur" "Ivysaur" "Venusaur" "Charmander" "Charmeleon")
declare -r API_URL="https://pokeapi.co/api/v2/pokemon/"
mkdir -p pokemon_data
for f in "${arr[@]}"; do
    OUTPUT_FILE="${f}.json"
    echo "Fetching data for ${f}..."
    curl -s -o "pokemon_data/${OUTPUT_FILE}" "${API_URL}${f}"
    echo "Saved data to pokemon_data/${f}.json"
    sleep 2
done