#!/usr/bin/env bash
# Extract and format Pokémon data using jq, awk, and sed

jq -r '. | "\(.name) \(.types[0].type.name) \(.weight) \(.height)"' data.json | \
awk '{printf "%s is of type %s, weighs %.1fkg, and is %.1fm tall.\n", $1, $2, $3/10, $4/10}' | \
sed 's/\b[a-z]/\u&/'
